# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Extracts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireObjectMapper', '= 5.2.1'
  pod 'ObjectMapper', '~> 3.4'

  # Pods for Extracts

  target 'ExtractsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExtractsUITests' do
    # Pods for testing
  end

end
